
[colors]
foreground = "#6c6f93"
background = "#1c1e26"
cursor_bg = "#fab795"
cursor_border = "#fab795"
cursor_fg = "#1c1e26"
selection_bg = "#6c6f93"
selection_fg = "#1c1e26"

ansi = ["#1c1e26","#e95678","#29d398","#fab795","#26bbd9","#ee64ae","#59e3e3","#6c6f93"]
brights = ["#1c1e26","#ec6a88","#3fdaa4","#fbc3a7","#3fc6de","#f075b7","#6be6e6","#6c6f93"]
  