
[colors]
foreground = "#6c6f93"
background = "#1c1e26"
cursor_bg = "#fab795"
cursor_border = "#fab795"
cursor_fg = "#1c1e26"
selection_bg = "#6c6f93"
selection_fg = "#1c1e26"
ansi = ["#1c1e26","#e95678","#09f7a0","#fac29a","#b877db","#f43e5c","#21bfc2","#6c6f93"]
brights = ["#1c1e26","#e95678","#09f7a0","#fac29a","#b877db","#f43e5c","#21bfc2","#6c6f93"]
  